--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Cosmoverse/NoVPN
build-by-default: true
branches:
- master
projects:
  NoVPN:
    path: ""
    libs:
      - src: cosmoverse/antivpn/AntiVPN
        version: ^1.0.0
...
